#!/bin/bash
#PBS -q qexp
#PBS -A DD-22-68
#PBS -l select=1:ncpus=36,vtune=2022_2_0
#PBS -l walltime=0:10:00
#PBS -m e
#PBS -N AVS-Advisor


cd $PBS_O_WORKDIR
ml intel-compilers/2022.1.0 CMake/3.23.1-GCCcore-11.3.0 Advisor/2021.4.0-GCCcore-10.3.0 VTune/2022.2.0-intel-2021b

[ -d build_advisor ] && rm -rf build_advisor
[ -d build_advisor ] || mkdir build_advisor
cd build_advisor

CC=icc CXX=icpc cmake ..
make


for calc in "ref" "batch" "line"; do
    rm -rf Advisor-$calc
    mkdir Advisor-$calc

    # Basic survey
    advixe-cl -collect survey -project-dir Advisor-$calc  -- ./mandelbrot -c $calc -s 4096


    # Roof line
    advixe-cl -collect tripcounts -flop -project-dir Advisor-$calc  -- ./mandelbrot -c $calc -s 4096
done
